name: bitdevsyde
static_sites:
- name: web
  github:
    branch: master
    repo: BitDevsYDE/bitdevsyde.org
  build_command: bundle install && bundle exec jekyll build --destination public
  output_dir: public
